"use client";

/**
 * Custom Exam Generator Workspace — real backend as of this pass
 * (app/api/exam/generate/route.ts): course list is fetched per-module (no
 * more MOCK_COURSES shown identically everywhere — that WAS the "cross-module
 * leakage" bug, since there was no real per-module fetch at all), exams are
 * generated by the LLM (40-60 QCM, enforced server-side by zod) and
 * permanently saved to `module_generated_exams`, and every saved exam is
 * listed under "Mes Examens" for instant, no-API-call re-viewing — the
 * "Semaine Bloquée" persistence layer.
 *
 * Layout mirrors the exact responsive fix already applied to the two other
 * workspace pages (app/dashboard/demo/[slug]/page.tsx and
 * app/dashboard/workspace/module/[moduleId]/page.tsx): flex-col + full-width
 * h-[70vh] panels on mobile, md:flex-row + fixed-width panels with internal
 * scroll on desktop.
 */

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import {
  AlertTriangle,
  CheckCircle2,
  FileQuestion,
  ListChecks,
  Loader2,
  RotateCcw,
  Sparkles,
  XCircle,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { Checkbox } from "@/components/ui/Checkbox";
import { ErrorState } from "@/components/ui/ErrorState";
import { useToast } from "@/components/ui/Toast";
import { WorkspaceTopbar } from "@/components/course/workspace/WorkspaceTopbar";
import type { StudioCourseSummary } from "@/types/studio-course";

type ExamState = "idle" | "generating" | "testing" | "results";

interface ExamOption {
  label: string;
  text: string;
  isCorrect: boolean;
  explanation: string;
}

interface ExamQuestion {
  id: string;
  vignette: string;
  options: ExamOption[];
  weakPointTag: string;
}

interface SavedExam {
  id: string;
  selectedCourses: { id: number; title: string }[];
  content: { questions: ExamQuestion[] };
  createdAt: string;
}

const MAX_ATTEMPTS = 5;

const panelShellClasses =
  "flex flex-col overflow-hidden rounded-3xl border border-gray-200 bg-white shadow-sm transition-all duration-300 dark:border-neutral-800 dark:bg-neutral-900";

export default function ExamGeneratorPage() {
  const params = useParams<{ id: string }>();
  const moduleId = Number(params.id);
  const { toast } = useToast();

  const [courses, setCourses] = useState<StudioCourseSummary[] | null>(null);
  const [coursesError, setCoursesError] = useState(false);
  const [coursesLoading, setCoursesLoading] = useState(true);
  const [retryToken, setRetryToken] = useState(0);
  const [selectedCourseIds, setSelectedCourseIds] = useState<Set<number>>(new Set());

  const [savedExams, setSavedExams] = useState<SavedExam[]>([]);
  const [activeExamId, setActiveExamId] = useState<string | null>(null);

  const [examState, setExamState] = useState<ExamState>("idle");
  const [answers, setAnswers] = useState<Record<string, string | null>>({});
  const [attempts, setAttempts] = useState(MAX_ATTEMPTS);
  const [isGenerating, setIsGenerating] = useState(false);

  const activeExam = useMemo(() => savedExams.find((e) => e.id === activeExamId) ?? null, [savedExams, activeExamId]);
  const questions = activeExam?.content.questions ?? [];

  const allSelected = courses !== null && courses.length > 0 && selectedCourseIds.size === courses.length;
  const someSelected = selectedCourseIds.size > 0 && !allSelected;

  useEffect(() => {
    if (!Number.isInteger(moduleId)) return;
    let cancelled = false;
    setCoursesLoading(true);
    setCoursesError(false);

    fetch(`/api/studio/courses?moduleId=${moduleId}`)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((body: { success: boolean; courses?: StudioCourseSummary[] }) => {
        if (cancelled) return;
        if (!body.success || !Array.isArray(body.courses)) throw new Error("Réponse invalide.");
        setCourses(body.courses);
        setSelectedCourseIds((prev) => new Set(body.courses!.filter((c) => prev.has(c.id)).map((c) => c.id)));
      })
      .catch(() => {
        if (!cancelled) setCoursesError(true);
      })
      .finally(() => {
        if (!cancelled) setCoursesLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [moduleId, retryToken]);

  // History fetch — scoped to THIS module only, fixing the "shows courses
  // from unrelated modules" bug at its root: there was never a real
  // per-module fetch of anything before this pass.
  useEffect(() => {
    if (!Number.isInteger(moduleId)) return;
    let cancelled = false;

    fetch(`/api/exam/generate?moduleId=${moduleId}`)
      .then((res) => (res.ok ? res.json() : Promise.reject()))
      .then((body: { success: boolean; exams?: SavedExam[] }) => {
        if (cancelled || !body.success || !Array.isArray(body.exams)) return;
        setSavedExams(body.exams);
        // Auto-resume the most recently generated exam (API returns oldest
        // first, so the last element is the newest) so coming back to this
        // page shows what the student was doing instead of the empty
        // generator form — the exam was always safely persisted server-side
        // in module_generated_exams, but requiring a manual click into "Mes
        // Examens" to see it again read exactly like the content was lost.
        if (body.exams.length > 0) {
          setActiveExamId(body.exams[body.exams.length - 1].id);
          setExamState("testing");
        }
      })
      .catch(() => {
        /* Non-fatal — the page still works, just without history pre-loaded. */
      });

    return () => {
      cancelled = true;
    };
  }, [moduleId]);

  function toggleAll() {
    if (!courses) return;
    setSelectedCourseIds(allSelected ? new Set() : new Set(courses.map((c) => c.id)));
  }

  function toggleCourse(id: number) {
    setSelectedCourseIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  async function generateExam(courseIds: number[], variation: boolean) {
    setAnswers({});
    setExamState("generating");
    setIsGenerating(true);
    try {
      const res = await fetch("/api/exam/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ moduleId, courseIds, variation }),
      });
      const body = await res.json().catch(() => null);
      if (!res.ok || !body?.success) {
        toast({ variant: "error", title: "Échec de la génération", description: body?.error ?? "Réessaie." });
        setExamState(variation ? "results" : "idle");
        return;
      }
      const exam = body.exam as SavedExam;
      setSavedExams((prev) => [...prev, exam]);
      setActiveExamId(exam.id);
      setExamState("testing");
    } catch {
      toast({ variant: "error", title: "Échec de la génération", description: "Impossible de contacter le serveur." });
      setExamState(variation ? "results" : "idle");
    } finally {
      setIsGenerating(false);
    }
  }

  function handleGenerate() {
    if (selectedCourseIds.size === 0) return;
    void generateExam([...selectedCourseIds], false);
  }

  function handleRegenerate() {
    if (attempts <= 0 || !activeExam) return;
    setAttempts((a) => a - 1);
    void generateExam(
      activeExam.selectedCourses.map((c) => c.id),
      true
    );
  }

  function handleViewExam(exam: SavedExam) {
    setActiveExamId(exam.id);
    setAnswers({});
    setExamState("testing");
  }

  function handleSelectAnswer(questionId: string, optionLabel: string) {
    setAnswers((prev) => ({ ...prev, [questionId]: optionLabel }));
  }

  const answeredCount = useMemo(() => Object.values(answers).filter(Boolean).length, [answers]);

  const score = useMemo(
    () =>
      questions.filter((q) => {
        const correct = q.options.find((o) => o.isCorrect);
        return correct && answers[q.id] === correct.label;
      }).length,
    [answers, questions]
  );

  const weakPoints = useMemo(() => {
    const tags = questions
      .filter((q) => {
        const correct = q.options.find((o) => o.isCorrect);
        return !correct || answers[q.id] !== correct.label;
      })
      .map((q) => q.weakPointTag);
    return Array.from(new Set(tags));
  }, [answers, questions]);

  return (
    <div className="flex h-screen flex-col overflow-hidden bg-gray-100 dark:bg-neutral-950">
      <WorkspaceTopbar title="Générateur d'Examen" />

      <div className="flex flex-1 flex-col gap-4 overflow-y-auto p-4 md:flex-row md:overflow-hidden">
        {/* Panneau Gauche — Sources + Historique */}
        <aside className={cn(panelShellClasses, "h-[70vh] w-full shrink-0 md:h-auto md:w-80")}>
          <div className="border-b border-gray-200 p-4 dark:border-neutral-800">
            <h2 className="text-sm font-bold text-gray-900 dark:text-gray-100">Cours du module</h2>
            <p className="mt-0.5 text-xs text-gray-500 dark:text-gray-400">
              {selectedCourseIds.size} / {courses?.length ?? 0} sélectionné{selectedCourseIds.size > 1 ? "s" : ""}
            </p>
            <label className="mt-3 flex cursor-pointer items-center gap-2.5 rounded-lg border border-gray-200 bg-gray-50 px-3 py-2 text-sm font-medium text-gray-700 dark:border-neutral-700 dark:bg-neutral-800 dark:text-gray-200">
              <Checkbox
                checked={allSelected ? true : someSelected ? "indeterminate" : false}
                onCheckedChange={toggleAll}
              />
              Sélectionner tout
            </label>
          </div>
          <div className="flex-1 overflow-y-auto p-2">
            {coursesLoading ? (
              <div className="space-y-2 p-2">
                {[0, 1, 2, 3].map((i) => (
                  <div key={i} className="h-11 animate-pulse rounded-xl bg-gray-100 dark:bg-neutral-800" />
                ))}
              </div>
            ) : coursesError ? (
              <div className="p-2">
                <ErrorState message="Échec du chargement des cours de ce module." onRetry={() => setRetryToken((t) => t + 1)} />
              </div>
            ) : !courses || courses.length === 0 ? (
              <p className="px-3 py-6 text-center text-xs text-gray-400 dark:text-gray-500">Aucun cours dans ce module pour l&apos;instant.</p>
            ) : (
              courses.map((course) => (
                <label
                  key={course.id}
                  className="flex cursor-pointer items-center gap-2.5 rounded-lg px-3 py-2.5 text-sm text-gray-700 transition-colors hover:bg-gray-50 dark:text-gray-300 dark:hover:bg-neutral-800"
                >
                  <Checkbox checked={selectedCourseIds.has(course.id)} onCheckedChange={() => toggleCourse(course.id)} />
                  {course.title}
                </label>
              ))
            )}

            {savedExams.length > 0 && (
              <div className="mt-2 border-t border-gray-200 pt-2 dark:border-neutral-800">
                <h3 className="px-3 py-1.5 text-xs font-bold uppercase tracking-wide text-gray-400 dark:text-gray-500">Mes Examens</h3>
                {savedExams.map((exam, index) => (
                  <button
                    key={exam.id}
                    type="button"
                    onClick={() => handleViewExam(exam)}
                    className={cn(
                      "flex w-full items-center justify-between rounded-lg px-3 py-2.5 text-left text-sm transition-colors",
                      activeExamId === exam.id
                        ? "bg-primary-50 font-semibold text-primary-700 dark:bg-primary-950/40 dark:text-primary-300"
                        : "text-gray-700 hover:bg-gray-50 dark:text-gray-300 dark:hover:bg-neutral-800"
                    )}
                  >
                    <span>Examen {index + 1}</span>
                    <span className="text-xs text-gray-400 dark:text-gray-500">{exam.content.questions.length} QCM</span>
                  </button>
                ))}
              </div>
            )}
          </div>
        </aside>

        {/* Panneau Droit — Exam Arena */}
        <main className={cn(panelShellClasses, "h-[70vh] w-full flex-1 md:h-auto")}>
          {examState === "idle" && (
            <div className="flex h-full flex-col items-center justify-center gap-4 p-8 text-center">
              <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-primary-50 dark:bg-primary-950/40">
                <FileQuestion className="h-8 w-8 text-primary-600 dark:text-primary-400" />
              </div>
              <div>
                <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100">Prêt à te tester ?</h3>
                <p className="mt-1 max-w-sm text-sm text-gray-500 dark:text-gray-400">
                  Sélectionne les cours à couvrir dans le panneau de gauche, puis génère un examen clinique complet.
                </p>
              </div>
              <Button size="lg" disabled={selectedCourseIds.size === 0 || isGenerating} onClick={handleGenerate}>
                Générer l&apos;examen (40-60 QCM)
              </Button>
              {selectedCourseIds.size === 0 && (
                <p className="text-xs text-gray-400 dark:text-gray-500">Sélectionne au moins un cours pour continuer.</p>
              )}
            </div>
          )}

          {examState === "generating" && (
            <div className="flex h-full flex-col items-center justify-center gap-6 p-8">
              <div className="relative flex h-16 w-16 items-center justify-center">
                <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-primary-400 opacity-30" />
                <Sparkles className="relative h-7 w-7 text-primary-600 dark:text-primary-400" />
              </div>
              <p className="max-w-sm text-center text-sm font-semibold text-gray-700 dark:text-gray-200">
                Création d&apos;un examen clinique type Faculté de Médecine Saad Dahlab (Blida)...
              </p>
              <div className="w-full max-w-md space-y-3">
                {[0, 1, 2].map((i) => (
                  <div key={i} className="space-y-2 rounded-xl border border-gray-200 p-4 dark:border-neutral-800">
                    <div className="h-3 w-3/4 animate-pulse rounded bg-gray-200 dark:bg-neutral-700" />
                    <div className="h-3 w-full animate-pulse rounded bg-gray-200 dark:bg-neutral-700" />
                    <div className="h-3 w-5/6 animate-pulse rounded bg-gray-200 dark:bg-neutral-700" />
                  </div>
                ))}
              </div>
            </div>
          )}

          {examState === "testing" && (
            <div className="flex h-full flex-col overflow-y-auto p-6 pb-28">
              <div className="mb-4 flex items-center justify-between gap-3">
                <h2 className="text-lg font-bold text-gray-900 dark:text-gray-100">Épreuve Clinique</h2>
                <Badge variant="outline">
                  {answeredCount} / {questions.length} répondues
                </Badge>
              </div>
              <div className="space-y-6">
                {questions.map((q, index) => (
                  <div key={q.id} className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900">
                    <p className="mb-4 text-sm font-medium leading-relaxed text-gray-800 dark:text-gray-100">
                      <span className="mr-2 font-bold text-primary-600 dark:text-primary-400">Q{index + 1}.</span>
                      {q.vignette}
                    </p>
                    <div className="space-y-2" role="radiogroup" aria-label={`Options question ${index + 1}`}>
                      {q.options.map((opt) => {
                        const selected = answers[q.id] === opt.label;
                        return (
                          <label
                            key={opt.label}
                            className={cn(
                              "flex cursor-pointer items-start gap-3 rounded-xl border p-3 text-sm transition-colors",
                              selected
                                ? "border-primary-500 bg-primary-50 dark:border-primary-500 dark:bg-primary-950/30"
                                : "border-gray-200 hover:bg-gray-50 dark:border-neutral-700 dark:hover:bg-neutral-800"
                            )}
                          >
                            <input
                              type="radio"
                              name={q.id}
                              className="sr-only"
                              checked={selected}
                              onChange={() => handleSelectAnswer(q.id, opt.label)}
                            />
                            <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-current text-[11px] font-bold text-gray-500 dark:text-gray-400">
                              {opt.label}
                            </span>
                            <span className="text-gray-700 dark:text-gray-200">{opt.text}</span>
                          </label>
                        );
                      })}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {examState === "results" && (
            <div className="flex h-full flex-col overflow-y-auto p-6">
              <div className="mb-6 rounded-2xl border-2 border-primary-200 bg-primary-50 p-5 text-center dark:border-primary-900/50 dark:bg-primary-950/20">
                <p className="text-xs font-bold uppercase tracking-wide text-primary-700 dark:text-primary-400">Score final</p>
                <p className="mt-1 text-4xl font-black text-gray-900 dark:text-white">
                  {score} / {questions.length}
                </p>
              </div>

              <div className="space-y-6">
                {questions.map((q, index) => {
                  const userAnswer = answers[q.id];
                  const correctOption = q.options.find((o) => o.isCorrect);
                  const isCorrect = !!correctOption && userAnswer === correctOption.label;
                  return (
                    <div key={q.id} className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-900">
                      <div className="mb-3 flex items-start justify-between gap-3">
                        <p className="text-sm font-medium leading-relaxed text-gray-800 dark:text-gray-100">
                          <span className="mr-2 font-bold text-primary-600 dark:text-primary-400">Q{index + 1}.</span>
                          {q.vignette}
                        </p>
                        {isCorrect ? (
                          <CheckCircle2 className="h-5 w-5 shrink-0 text-emerald-500" />
                        ) : (
                          <XCircle className="h-5 w-5 shrink-0 text-rose-500" />
                        )}
                      </div>

                      <div className="space-y-2">
                        {q.options.map((opt) => {
                          const isUserChoice = userAnswer === opt.label;
                          return (
                            <div
                              key={opt.label}
                              className={cn(
                                "flex items-start gap-3 rounded-xl border p-3 text-sm",
                                isUserChoice && opt.isCorrect && "border-emerald-500 bg-emerald-50 dark:border-emerald-600 dark:bg-emerald-950/30",
                                isUserChoice && !opt.isCorrect && "border-rose-500 bg-rose-50 dark:border-rose-600 dark:bg-rose-950/30",
                                !isUserChoice && opt.isCorrect && "border-dashed border-emerald-400 bg-white dark:bg-neutral-900",
                                !isUserChoice && !opt.isCorrect && "border-gray-200 dark:border-neutral-800"
                              )}
                            >
                              <span className="flex h-5 w-5 shrink-0 items-center justify-center rounded-full border border-current text-[11px] font-bold text-gray-500 dark:text-gray-400">
                                {opt.label}
                              </span>
                              <span className="flex-1 text-gray-700 dark:text-gray-200">{opt.text}</span>
                              {isUserChoice && opt.isCorrect && <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" />}
                              {isUserChoice && !opt.isCorrect && <XCircle className="h-4 w-4 shrink-0 text-rose-600" />}
                              {!isUserChoice && opt.isCorrect && (
                                <Badge variant="outline" className="shrink-0 text-[10px]">
                                  Bonne réponse
                                </Badge>
                              )}
                            </div>
                          );
                        })}
                      </div>

                      <div className="mt-4 rounded-xl border border-blue-100 bg-blue-50 p-4 dark:border-blue-900/40 dark:bg-blue-950/20">
                        <p className="mb-2 flex items-center gap-1.5 text-xs font-bold uppercase tracking-wide text-blue-700 dark:text-blue-400">
                          <Sparkles className="h-3.5 w-3.5" /> Explication détaillée
                        </p>
                        <ul className="space-y-1.5 text-sm text-gray-700 dark:text-gray-300">
                          {q.options.map((opt) => (
                            <li key={opt.label}>
                              <span className="font-semibold">{opt.label}.</span> {opt.explanation}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  );
                })}
              </div>

              {weakPoints.length > 0 && (
                <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-900/40 dark:bg-amber-950/20">
                  <p className="mb-2 flex items-center gap-2 text-sm font-bold text-amber-800 dark:text-amber-300">
                    <AlertTriangle className="h-4 w-4" /> Points Faibles Identifiés
                  </p>
                  <ul className="list-disc space-y-1 pl-5 text-sm text-amber-900 dark:text-amber-200">
                    {weakPoints.map((point) => (
                      <li key={point}>{point}</li>
                    ))}
                  </ul>
                </div>
              )}

              <div className="mt-6">
                <Button variant="outline" className="w-full" onClick={handleRegenerate} disabled={attempts <= 0 || isGenerating}>
                  {isGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : <RotateCcw className="h-4 w-4" />}
                  {attempts > 0
                    ? `Régénérer un nouvel examen (${attempts} tentative${attempts > 1 ? "s" : ""} restante${attempts > 1 ? "s" : ""})`
                    : "Aucune tentative restante"}
                </Button>
              </div>
            </div>
          )}
        </main>
      </div>

      {examState === "testing" && (
        <div className="fixed inset-x-0 bottom-0 z-40 flex items-center justify-between gap-4 border-t border-gray-200 bg-white/95 p-4 backdrop-blur dark:border-neutral-800 dark:bg-neutral-900/95">
          <p className="hidden text-sm text-gray-500 dark:text-gray-400 sm:block">
            <ListChecks className="mr-1.5 inline h-4 w-4" />
            {answeredCount} / {questions.length} questions répondues
          </p>
          <Button className="w-full sm:w-auto" onClick={() => setExamState("results")}>
            Afficher la correction
          </Button>
        </div>
      )}
    </div>
  );
}
