"use client";

/**
 * Custom Exam Generator Workspace — real backend as of this pass
 * (app/api/exam/generate/route.ts): course list is fetched per-module (no
 * more MOCK_COURSES shown identically everywhere — that WAS the "cross-module
 * leakage" bug, since there was no real per-module fetch at all), exams are
 * generated by the LLM (40-60 QCM, enforced server-side by zod) and
 * permanently saved to `module_generated_exams`, and every saved exam is
 * listed under "Mes Examens" for instant, no-API-call re-viewing — the
 * "Semaine Bloquée" persistence layer.
 *
 * Layout mirrors the exact responsive fix already applied to the two other
 * workspace pages (app/dashboard/demo/[slug]/page.tsx and
 * app/dashboard/workspace/module/[moduleId]/page.tsx): flex-col + full-width
 * h-[70vh] panels on mobile, md:flex-row + fixed-width panels with internal
 * scroll on desktop.
 */

import { useEffect, useMemo, useState } from "react";
import { useParams } from "next/navigation";
import { motion, AnimatePresence } from "framer-motion";
import {
  AlertTriangle,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  FilePlus2,
  FileQuestion,
  ListChecks,
  Loader2,
  RotateCcw,
  Sparkles,
  Trophy,
  XCircle,
} from "lucide-react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/Button";
import { Badge } from "@/components/ui/Badge";
import { Checkbox } from "@/components/ui/Checkbox";
import { ErrorState } from "@/components/ui/ErrorState";
import { ProgressRing } from "@/components/ui/ProgressRing";
import { useToast } from "@/components/ui/Toast";
import { WorkspaceTopbar } from "@/components/course/workspace/WorkspaceTopbar";
import type { StudioCourseSummary } from "@/types/studio-course";
import { useLanguage } from "@/providers/LanguageProvider";
import { tExam } from "@/lib/translations/exam";
import { useMediaQuery } from "@/hooks/useMediaQuery";
import { SourcesResultsTabs, type SourcesResultsTab } from "@/components/course/workspace/SourcesResultsTabs";
import { FullscreenToggleButton } from "@/components/ui/FullscreenToggleButton";
import { FullscreenViewerModal } from "@/components/ui/FullscreenViewerModal";
import { ReferenceExamUploader } from "@/components/course/workspace/exam/ReferenceExamUploader";
import { ExamTimer } from "@/components/course/workspace/exam/ExamTimer";
import { ExamQuestionNavigator } from "@/components/course/workspace/exam/ExamQuestionNavigator";
import type { ExamStyleProfile } from "@/lib/ai/exam-schemas";

type ExamState = "idle" | "generating" | "testing" | "results";

interface ExamOption {
  label: string;
  text: string;
  isCorrect: boolean;
  explanation: string;
}

interface ExamQuestion {
  id: string;
  vignette: string;
  options: ExamOption[];
  weakPointTag: string;
}

interface SavedExam {
  id: string;
  selectedCourses: { id: number; title: string }[];
  content: { questions: ExamQuestion[] };
  createdAt: string;
}

/** One persisted sitting of a saved exam — see app/api/exam/attempts/route.ts. `score`/`totalQuestions` are the server's own recomputed grading, never trusted from whatever the client last held in state. */
interface ExamAttempt {
  id: string;
  examId: string;
  answers: Record<string, string | null>;
  score: number;
  totalQuestions: number;
  createdAt: string;
}

const MAX_ATTEMPTS = 5;

const panelShellClasses =
  "glass-card flex flex-col overflow-hidden rounded-3xl shadow-glass transition-all duration-300 dark:shadow-glass-dark";

const RESULTS_STAGGER_VARIANTS = { hidden: {}, show: { transition: { staggerChildren: 0.05 } } };
const RESULT_CARD_VARIANTS = { hidden: { opacity: 0, y: 10 }, show: { opacity: 1, y: 0 } };

export default function ExamGeneratorPage() {
  const params = useParams<{ id: string }>();
  const moduleId = Number(params.id);
  const { toast } = useToast();
  const { language } = useLanguage();

  const [courses, setCourses] = useState<StudioCourseSummary[] | null>(null);
  const [coursesError, setCoursesError] = useState(false);
  const [coursesLoading, setCoursesLoading] = useState(true);
  const [retryToken, setRetryToken] = useState(0);
  const [selectedCourseIds, setSelectedCourseIds] = useState<Set<number>>(new Set());
  // "Examen Guidé par le Style Prof" — extracted from an optional
  // student-uploaded reference exam (ReferenceExamUploader), threaded
  // verbatim into generateExam's POST body below. Never persisted here
  // beyond this component's own state — a page refresh simply forgets it,
  // same as every other in-progress selection on this page.
  const [styleProfile, setStyleProfile] = useState<ExamStyleProfile | null>(null);

  const [savedExams, setSavedExams] = useState<SavedExam[]>([]);
  const [activeExamId, setActiveExamId] = useState<string | null>(null);

  const [examState, setExamState] = useState<ExamState>("idle");
  const [answers, setAnswers] = useState<Record<string, string | null>>({});
  // MAX_ATTEMPTS is only the initial/pre-load placeholder and display-fallback
  // cap reference now — the moment either the GET-history effect below or a
  // generateExam response reports the server's real regenerationsRemaining
  // (from profiles.module_exam_regenerations_used via
  // app/api/exam/generate/route.ts), THAT becomes the live source of truth.
  // Never decremented optimistically client-side anymore — see
  // handleRegenerate and generateExam.
  const [attempts, setAttempts] = useState(MAX_ATTEMPTS);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isSavingAttempt, setIsSavingAttempt] = useState(false);

  // Latest saved attempt per examId — see app/api/exam/attempts/route.ts.
  // Keyed by examId (not a plain array) so handleViewExam/the auto-resume
  // effect below can look one up in O(1) instead of re-scanning on every
  // switch between "Mes Examens" entries.
  const [attemptsByExamId, setAttemptsByExamId] = useState<Record<string, ExamAttempt>>({});

  const activeExam = useMemo(() => savedExams.find((e) => e.id === activeExamId) ?? null, [savedExams, activeExamId]);
  const questions = useMemo(() => activeExam?.content.questions ?? [], [activeExam]);

  // "Un-contre-un" testing cockpit — one question in focus at a time
  // (instead of one giant scroll), with a jump-to-any-question navigator.
  // Reset to 0 whenever a FRESH testing sitting starts (a new/regenerated
  // exam, or opening a saved exam that has no attempt yet) — see
  // generateExam and handleViewExam below. `slideDirection` only drives the
  // enter/exit animation (+1 going forward, -1 going back); it never affects
  // which question is shown.
  const [currentQuestionIndex, setCurrentQuestionIndex] = useState(0);
  const [slideDirection, setSlideDirection] = useState(1);

  function goToQuestion(index: number) {
    if (index < 0 || index >= questions.length) return;
    setSlideDirection(index > currentQuestionIndex ? 1 : -1);
    setCurrentQuestionIndex(index);
  }

  // Mobile-first UX rework — below `md`, aside/main never render side by
  // side (there was too little room for either once one held a real
  // generated exam). A "Sources" / "Résultats" tab switch decides which
  // single panel shows: "Sources" groups course selection + the generate
  // button; "Résultats" groups "Mes Examens" + whichever exam is open (with
  // its own fullscreen toggle). Desktop (md:+) keeps the original permanent
  // side-by-side split, both panels always visible, unchanged.
  const isDesktopOrTablet = useMediaQuery("(min-width: 768px)");
  const [mobileTab, setMobileTab] = useState<SourcesResultsTab>("sources");
  // Lets the open exam (testing or results view) expand into the portaled
  // FullscreenViewerModal below — shared between desktop's `main` and
  // mobile's "Résultats" tab triggers (only one of the two ever mounts at a
  // time), with a single modal instance actually rendering the content.
  const [isExamFullscreen, setIsExamFullscreen] = useState(false);

  const allSelected = courses !== null && courses.length > 0 && selectedCourseIds.size === courses.length;
  const someSelected = selectedCourseIds.size > 0 && !allSelected;

  useEffect(() => {
    if (!Number.isInteger(moduleId)) return;
    let cancelled = false;
    setCoursesLoading(true);
    setCoursesError(false);

    fetch(`/api/studio/courses?moduleId=${moduleId}`)
      .then((res) => {
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        return res.json();
      })
      .then((body: { success: boolean; courses?: StudioCourseSummary[] }) => {
        if (cancelled) return;
        if (!body.success || !Array.isArray(body.courses)) throw new Error("Réponse invalide.");
        setCourses(body.courses);
        setSelectedCourseIds((prev) => new Set(body.courses!.filter((c) => prev.has(c.id)).map((c) => c.id)));
      })
      .catch(() => {
        if (!cancelled) setCoursesError(true);
      })
      .finally(() => {
        if (!cancelled) setCoursesLoading(false);
      });

    return () => {
      cancelled = true;
    };
  }, [moduleId, retryToken]);

  // History fetch — scoped to THIS module only, fixing the "shows courses
  // from unrelated modules" bug at its root: there was never a real
  // per-module fetch of anything before this pass. Fetches saved exams AND
  // their attempts together (not one after the other) so the auto-resume
  // decision below is made with both in hand — fetching attempts in a
  // separate effect risked a visible flash of the blank "testing" state
  // before a previously-saved attempt had a chance to load and restore it.
  useEffect(() => {
    if (!Number.isInteger(moduleId)) return;
    let cancelled = false;

    Promise.all([
      fetch(`/api/exam/generate?moduleId=${moduleId}`).then((res) => (res.ok ? res.json() : Promise.reject())),
      fetch(`/api/exam/attempts?moduleId=${moduleId}`).then((res) => (res.ok ? res.json() : { success: true, attempts: [] })),
    ])
      .then(
        ([examsBody, attemptsBody]: [
          { success: boolean; exams?: SavedExam[]; regenerationsUsed?: number; regenerationsRemaining?: number },
          { success: boolean; attempts?: ExamAttempt[] },
        ]) => {
          if (cancelled || !examsBody.success || !Array.isArray(examsBody.exams)) return;
          setSavedExams(examsBody.exams);

          // Sync the "Régénérer" counter to server truth ONCE on load —
          // replaces the initial useState(MAX_ATTEMPTS) placeholder with the
          // real remaining count (profiles.module_exam_regenerations_used-
          // derived) instead of leaving every page mount/reload showing a
          // full 5 regardless of how many the student already used.
          if (typeof examsBody.regenerationsRemaining === "number") {
            setAttempts(examsBody.regenerationsRemaining);
          }

          // Reduce to the LATEST attempt per examId — attempts are returned
          // oldest-first (same convention as exams), so a later entry for
          // the same examId simply overwrites the earlier one here.
          const latestByExamId: Record<string, ExamAttempt> = {};
          if (attemptsBody.success && Array.isArray(attemptsBody.attempts)) {
            for (const attempt of attemptsBody.attempts) latestByExamId[attempt.examId] = attempt;
          }
          setAttemptsByExamId(latestByExamId);

          // Auto-resume the most recently generated exam (API returns oldest
          // first, so the last element is the newest) so coming back to this
          // page shows what the student was doing instead of the empty
          // generator form — the exam was always safely persisted server-side
          // in module_generated_exams, but requiring a manual click into "Mes
          // Examens" to see it again read exactly like the content was lost.
          // If a saved attempt exists for it, restore straight into the
          // correction view instead of a blank re-take.
          if (examsBody.exams.length > 0) {
            const mostRecentExam = examsBody.exams[examsBody.exams.length - 1];
            setActiveExamId(mostRecentExam.id);
            const savedAttempt = latestByExamId[mostRecentExam.id];
            if (savedAttempt) {
              setAnswers(savedAttempt.answers);
              setExamState("results");
            } else {
              setExamState("testing");
              setCurrentQuestionIndex(0);
            }
            setMobileTab("results");
          }
        }
      )
      .catch(() => {
        /* Non-fatal — the page still works, just without history pre-loaded. */
      });

    return () => {
      cancelled = true;
    };
  }, [moduleId]);

  function toggleAll() {
    if (!courses) return;
    setSelectedCourseIds(allSelected ? new Set() : new Set(courses.map((c) => c.id)));
  }

  function toggleCourse(id: number) {
    setSelectedCourseIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  }

  async function generateExam(courseIds: number[], variation: boolean) {
    setAnswers({});
    setExamState("generating");
    setIsGenerating(true);
    try {
      const res = await fetch("/api/exam/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ moduleId, courseIds, variation, ...(styleProfile ? { styleProfile } : {}) }),
      });
      const body = await res.json().catch(() => null);
      // Server truth for the "Régénérer" quota, synced whenever the API
      // includes it — on the SUCCESS path (a fresh regeneration was just
      // reserved) and on the 403 cap-reached error path alike (see
      // app/api/exam/generate/route.ts's POST handler), so the local
      // `attempts` counter can never claim more remain than the server
      // actually has left. Replaces the old purely-optimistic
      // `setAttempts((a) => a - 1)` that ran before the API call even
      // resolved and was never reconciled with the real count.
      if (typeof body?.regenerationsRemaining === "number") {
        setAttempts(body.regenerationsRemaining);
      }
      if (!res.ok || !body?.success) {
        toast({
          variant: "error",
          title: tExam("generationFailedTitle", language),
          description: body?.error ?? tExam("generationFailedFallbackDescription", language),
        });
        setExamState(variation ? "results" : "idle");
        return;
      }
      const exam = body.exam as SavedExam;
      setSavedExams((prev) => [...prev, exam]);
      setActiveExamId(exam.id);
      setExamState("testing");
      setCurrentQuestionIndex(0);
      // Dès qu'un examen est généré, bascule automatiquement sur l'onglet
      // "Résultats" (mobile uniquement — no-op on desktop, both panels
      // already visible there).
      setMobileTab("results");
    } catch {
      toast({
        variant: "error",
        title: tExam("generationFailedTitle", language),
        description: tExam("generationFailedNetworkDescription", language),
      });
      setExamState(variation ? "results" : "idle");
    } finally {
      setIsGenerating(false);
    }
  }

  function handleGenerate() {
    if (selectedCourseIds.size === 0) return;
    void generateExam([...selectedCourseIds], false);
  }

  function handleRegenerate() {
    if (attempts <= 0 || !activeExam) return;
    // No optimistic local decrement anymore — `attempts` is synced from the
    // server's authoritative regenerationsRemaining once generateExam's
    // response comes back (success or 403 cap-reached alike).
    void generateExam(
      activeExam.selectedCourses.map((c) => c.id),
      true
    );
  }

  /** "Générer un nouvel examen" — distinct from Régénérer (which reuses activeExam.selectedCourses): returns to course selection so the student can pick a DIFFERENT set of courses, without touching activeExamId/savedExams/attemptsByExamId (so "Mes Examens" history stays untouched) or clearing the prior selection (consistent with this codebase's other "back" flows, which let the student see and adjust their last pick rather than starting from a blank slate). */
  function handleStartOver() {
    setExamState("idle");
  }

  function handleViewExam(exam: SavedExam) {
    setActiveExamId(exam.id);
    // Restore a previously saved attempt straight into the correction view
    // instead of resetting to a blank re-take — matches the auto-resume
    // effect's own behavior for the most recent exam.
    const savedAttempt = attemptsByExamId[exam.id];
    if (savedAttempt) {
      setAnswers(savedAttempt.answers);
      setExamState("results");
    } else {
      setAnswers({});
      setExamState("testing");
      setCurrentQuestionIndex(0);
    }
    setMobileTab("results");
  }

  /** "Afficher la correction" — saves the attempt server-side (recomputes score from the exam's own canonical content, see app/api/exam/attempts/route.ts) BEFORE switching to the results view. A save failure never blocks the student from seeing their own already-computed local correction — it just means the attempt won't be there if they come back later, surfaced via a toast rather than a silent loss. */
  async function handleFinishExam() {
    if (!activeExam) {
      setExamState("results");
      return;
    }
    setIsSavingAttempt(true);
    try {
      const res = await fetch("/api/exam/attempts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ examId: activeExam.id, answers }),
      });
      const body = await res.json().catch(() => null);
      if (res.ok && body?.success) {
        setAttemptsByExamId((prev) => ({ ...prev, [activeExam.id]: body.attempt as ExamAttempt }));
      } else {
        toast({
          variant: "error",
          title: tExam("resultsNotSavedTitle", language),
          description: body?.error ?? tExam("resultsNotSavedFallbackDescription", language),
        });
      }
    } catch {
      toast({
        variant: "error",
        title: tExam("resultsNotSavedTitle", language),
        description: tExam("resultsNotSavedNetworkDescription", language),
      });
    } finally {
      setIsSavingAttempt(false);
      setExamState("results");
    }
  }

  function handleSelectAnswer(questionId: string, optionLabel: string) {
    setAnswers((prev) => ({ ...prev, [questionId]: optionLabel }));
  }

  const answeredCount = useMemo(() => Object.values(answers).filter(Boolean).length, [answers]);

  const score = useMemo(
    () =>
      questions.filter((q) => {
        const correct = q.options.find((o) => o.isCorrect);
        return correct && answers[q.id] === correct.label;
      }).length,
    [answers, questions]
  );

  const weakPoints = useMemo(() => {
    const tags = questions
      .filter((q) => {
        const correct = q.options.find((o) => o.isCorrect);
        return !correct || answers[q.id] !== correct.label;
      })
      .map((q) => q.weakPointTag);
    return Array.from(new Set(tags));
  }, [answers, questions]);

  const courseHeaderBlock = (
    <div className="border-b border-border p-4">
      <div className="flex items-center gap-2.5">
        <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-primary-50 text-primary-600 shadow-sm dark:bg-primary-950/40 dark:text-primary-400">
          <FileQuestion className="h-4 w-4" />
        </span>
        <div>
          <h2 className="text-sm font-bold text-foreground">{tExam("coursesOfModule", language)}</h2>
          <p className="text-xs text-muted-foreground">
            {selectedCourseIds.size} / {courses?.length ?? 0} sélectionné{selectedCourseIds.size > 1 ? "s" : ""}
          </p>
        </div>
      </div>
      <label className="mt-3 flex min-h-11 cursor-pointer items-center gap-2.5 rounded-lg border border-border bg-accent/40 px-3 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent">
        <Checkbox checked={allSelected ? true : someSelected ? "indeterminate" : false} onCheckedChange={toggleAll} />
        Sélectionner tout
      </label>
    </div>
  );

  const courseListContent = coursesLoading ? (
    <div className="space-y-2 p-2">
      {[0, 1, 2, 3].map((i) => (
        <div key={i} className="h-11 animate-pulse rounded-xl bg-muted" />
      ))}
    </div>
  ) : coursesError ? (
    <div className="p-2">
      <ErrorState message="Échec du chargement des cours de ce module." onRetry={() => setRetryToken((t) => t + 1)} />
    </div>
  ) : !courses || courses.length === 0 ? (
    <p className="px-3 py-6 text-center text-xs text-muted-foreground">Aucun cours dans ce module pour l&apos;instant.</p>
  ) : (
    courses.map((course) => {
      const selected = selectedCourseIds.has(course.id);
      return (
        <label
          key={course.id}
          className={cn(
            "flex min-h-11 cursor-pointer items-center gap-2.5 rounded-xl border px-3 py-2.5 text-sm font-medium transition-all duration-200 active:scale-[0.99]",
            selected
              ? "border-primary-300 bg-primary-50 text-primary-800 shadow-glow dark:border-primary-800 dark:bg-primary-950/30 dark:text-primary-200"
              : "border-transparent text-foreground hover:-translate-y-0.5 hover:border-border hover:bg-accent hover:shadow-soft"
          )}
        >
          <Checkbox checked={selected} onCheckedChange={() => toggleCourse(course.id)} />
          {course.title}
        </label>
      );
    })
  );

  const savedExamsContent = savedExams.length > 0 && (
    <>
      <h3 className="px-3 py-1.5 text-xs font-bold uppercase tracking-wide text-muted-foreground">Mes Examens</h3>
      {savedExams.map((exam, index) => {
        const savedAttempt = attemptsByExamId[exam.id];
        return (
          <button
            key={exam.id}
            type="button"
            onClick={() => handleViewExam(exam)}
            className={cn(
              "flex min-h-11 w-full items-center justify-between gap-2 rounded-xl px-3 py-2.5 text-left text-sm transition-all duration-200 active:scale-[0.98]",
              activeExamId === exam.id
                ? "border border-primary-300 bg-primary-50 font-semibold text-primary-800 shadow-glow dark:border-primary-800 dark:bg-primary-950/30 dark:text-primary-200"
                : "border border-transparent text-foreground hover:-translate-y-0.5 hover:border-border hover:bg-accent hover:shadow-soft"
            )}
          >
            <span className="min-w-0 truncate">Examen {index + 1}</span>
            <span className="flex shrink-0 items-center gap-1.5">
              {savedAttempt && (
                <Badge variant={savedAttempt.score / savedAttempt.totalQuestions >= 0.5 ? "success" : "danger"}>
                  {savedAttempt.score}/{savedAttempt.totalQuestions}
                </Badge>
              )}
              <span className="text-xs text-muted-foreground">{exam.content.questions.length} QCM</span>
            </span>
          </button>
        );
      })}
    </>
  );

  // Compact course-list + button combo used ONLY by the mobile "Sources"
  // tab — desktop keeps its own bigger, decorative idleContent card below
  // instead (unchanged), since desktop already has the room to spare.
  const generateButtonBlock = (
    <div className="shrink-0 border-t border-border p-4">
      <Button
        size="lg"
        disabled={selectedCourseIds.size === 0 || isGenerating}
        onClick={handleGenerate}
        className="min-h-12 w-full whitespace-normal text-center leading-snug shadow-glow"
      >
        {isGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : <Sparkles className="h-4 w-4" />}
        Générer l&apos;examen
      </Button>
      <p className="mt-2 text-center text-xs text-muted-foreground">40 à 60 QCM générés par l&apos;IA</p>
      {selectedCourseIds.size === 0 && (
        <p className="mt-1 text-center text-xs text-muted-foreground">Sélectionne au moins un cours pour continuer.</p>
      )}
    </div>
  );

  const idleContent = (
    <motion.div
      key="idle"
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.35, ease: [0.22, 1, 0.36, 1] }}
      className="flex h-full flex-col items-center justify-center gap-4 overflow-y-auto p-6 text-center sm:p-8"
    >
      <div className="relative flex h-20 w-20 shrink-0 animate-float items-center justify-center rounded-3xl bg-primary-50 shadow-glow dark:bg-primary-950/40">
        <span aria-hidden className="absolute inset-0 rounded-3xl bg-primary-400/20 blur-xl" />
        <FileQuestion className="relative h-9 w-9 text-primary-600 dark:text-primary-400" />
      </div>
      <div>
        <h3 className="text-xl font-bold text-foreground">Prêt à te tester ?</h3>
        <p className="mt-1 max-w-sm text-sm text-muted-foreground">
          Sélectionne les cours à couvrir dans le panneau de gauche, puis génère un examen clinique complet.
        </p>
      </div>
      <div className="flex flex-col items-center gap-1.5">
        <Button
          size="lg"
          disabled={selectedCourseIds.size === 0 || isGenerating}
          onClick={handleGenerate}
          className="min-h-12 max-w-full whitespace-normal text-center leading-snug shadow-glow"
        >
          <Sparkles className="h-4 w-4" />
          Générer l&apos;examen
        </Button>
        <p className="text-xs text-muted-foreground">40 à 60 QCM générés par l&apos;IA</p>
      </div>
      {selectedCourseIds.size === 0 && <p className="text-xs text-muted-foreground">Sélectionne au moins un cours pour continuer.</p>}
    </motion.div>
  );

  const generatingContent = (
    <motion.div
      key="generating"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.3 }}
      className="flex h-full flex-col items-center justify-center gap-6 overflow-y-auto p-6 sm:p-8"
    >
      <div className="relative flex h-20 w-20 items-center justify-center">
        <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-primary-400 opacity-30" />
        <span aria-hidden className="absolute inset-0 rounded-full bg-primary-400/20 blur-xl" />
        <motion.div
          animate={{ rotate: 360 }}
          transition={{ duration: 3, repeat: Infinity, ease: "linear" }}
          className="relative flex h-14 w-14 items-center justify-center rounded-2xl bg-primary-50 shadow-glow dark:bg-primary-950/40"
        >
          <Sparkles className="h-7 w-7 text-primary-600 dark:text-primary-400" />
        </motion.div>
      </div>
      <p className="max-w-sm text-center text-sm font-semibold text-foreground">
        Création d&apos;un examen clinique type Faculté de Médecine Saad Dahlab (Blida)...
      </p>
      {/* Purely ambient — a fixed row of skeleton cards revealing on a
          staggered delay, NOT tied to any real per-question progress signal
          (the backend returns the whole exam in one response; sometimes
          instantly from cache). Never claims a specific question count or
          step is "done now" — that would be fabricated given caching/pooling
          upstream (see app/api/exam/generate/route.ts). */}
      <div className="w-full max-w-md space-y-3">
        {[0, 1, 2].map((i) => (
          <motion.div
            key={i}
            initial={{ opacity: 0, y: 8 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: i * 0.5, repeat: Infinity, repeatType: "reverse", repeatDelay: 1 }}
            className="space-y-2 rounded-xl border border-border bg-accent/40 p-4"
          >
            <div className="h-3 w-3/4 animate-pulse rounded bg-muted" />
            <div className="h-3 w-full animate-pulse rounded bg-muted" />
            <div className="h-3 w-5/6 animate-pulse rounded bg-muted" />
          </motion.div>
        ))}
      </div>
    </motion.div>
  );

  // Split into "inner content" (reused, unwrapped, inside the portaled
  // FullscreenViewerModal) + the wrapping motion.div (used only for the
  // normal, non-fullscreen panel, which needs its own bounded height/scroll
  // — the modal provides its own single scroll region instead).
  const currentQuestion = questions[currentQuestionIndex] as ExamQuestion | undefined;

  const testingInnerContent = (
    <>
      <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
        <h2 className="text-lg font-bold text-foreground">Épreuve Clinique</h2>
        <div className="flex items-center gap-2">
          <ExamTimer key={activeExamId} />
          <ProgressRing
            completed={answeredCount}
            total={questions.length}
            size={40}
            strokeWidth={4}
            label={
              <span className="text-[10px] font-bold text-foreground">
                {answeredCount}/{questions.length}
              </span>
            }
            aria-label={`${answeredCount} sur ${questions.length} questions répondues`}
          />
        </div>
      </div>

      <ExamQuestionNavigator
        total={questions.length}
        currentIndex={currentQuestionIndex}
        isAnswered={(i) => Boolean(answers[questions[i]?.id])}
        onJump={goToQuestion}
        className="mb-4"
      />

      {currentQuestion && (
        <AnimatePresence mode="wait" custom={slideDirection}>
          <motion.div
            key={currentQuestion.id}
            custom={slideDirection}
            initial={{ x: slideDirection > 0 ? 60 : -60, opacity: 0 }}
            animate={{ x: 0, opacity: 1 }}
            exit={{ x: slideDirection > 0 ? -60 : 60, opacity: 0 }}
            transition={{ duration: 0.25, ease: [0.22, 1, 0.36, 1] }}
            drag="x"
            dragConstraints={{ left: 0, right: 0 }}
            dragElastic={0.15}
            onDragEnd={(_event, info) => {
              if (info.offset.x < -80) goToQuestion(currentQuestionIndex + 1);
              else if (info.offset.x > 80) goToQuestion(currentQuestionIndex - 1);
            }}
            className="glass-card cursor-grab touch-pan-y rounded-2xl border border-border p-4 shadow-soft active:cursor-grabbing sm:p-6"
          >
            <div className="mb-4 flex items-center gap-2">
              <Badge variant="primary">Q{currentQuestionIndex + 1} / {questions.length}</Badge>
              {answers[currentQuestion.id] && <Badge variant="success">Répondue</Badge>}
            </div>
            <p className="mb-5 text-base font-medium leading-relaxed text-foreground">{currentQuestion.vignette}</p>
            <div className="space-y-2.5" role="radiogroup" aria-label={`Options question ${currentQuestionIndex + 1}`}>
              {currentQuestion.options.map((opt) => {
                const selected = answers[currentQuestion.id] === opt.label;
                return (
                  <label
                    key={opt.label}
                    className={cn(
                      "flex min-h-12 cursor-pointer items-center gap-3 rounded-xl border p-3 text-sm transition-all duration-200 active:scale-[0.99]",
                      selected
                        ? "border-primary-500 bg-primary-50 shadow-glow dark:border-primary-500 dark:bg-primary-950/30"
                        : "border-border hover:-translate-y-0.5 hover:bg-accent hover:shadow-soft"
                    )}
                  >
                    <input
                      type="radio"
                      name={currentQuestion.id}
                      className="sr-only"
                      checked={selected}
                      onChange={() => handleSelectAnswer(currentQuestion.id, opt.label)}
                    />
                    <span
                      className={cn(
                        "flex h-7 w-7 shrink-0 items-center justify-center rounded-full border text-xs font-bold",
                        selected ? "border-primary-600 bg-primary-600 text-white" : "border-current text-muted-foreground"
                      )}
                    >
                      {opt.label}
                    </span>
                    <span className="text-foreground">{opt.text}</span>
                  </label>
                );
              })}
            </div>
          </motion.div>
        </AnimatePresence>
      )}

      <div className="mt-5 flex items-center justify-between gap-3">
        <Button
          variant="outline"
          size="sm"
          className="min-h-12"
          disabled={currentQuestionIndex === 0}
          onClick={() => goToQuestion(currentQuestionIndex - 1)}
        >
          <ChevronLeft className="h-4 w-4" />
          Précédente
        </Button>
        <Button
          variant="outline"
          size="sm"
          className="min-h-12"
          disabled={currentQuestionIndex >= questions.length - 1}
          onClick={() => goToQuestion(currentQuestionIndex + 1)}
        >
          Suivante
          <ChevronRight className="h-4 w-4" />
        </Button>
      </div>
    </>
  );

  const testingContent = (
    <motion.div
      key="testing"
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.3 }}
      className="flex h-full flex-col overflow-y-auto p-4 pb-[calc(9rem+env(safe-area-inset-bottom))] sm:p-6"
    >
      {testingInnerContent}
    </motion.div>
  );

  const scorePct = questions.length > 0 ? Math.round((score / questions.length) * 100) : 0;
  const scoreTone = scorePct >= 80 ? "text-emerald-600 dark:text-emerald-400" : scorePct >= 50 ? "text-amber-600 dark:text-amber-400" : "text-rose-600 dark:text-rose-400";

  const resultsInnerContent = (
    <>
      <div className="glass-card mb-6 flex flex-col items-center gap-3 rounded-3xl border border-border p-6 text-center shadow-glow sm:flex-row sm:justify-center sm:gap-6">
        <ProgressRing
          completed={score}
          total={Math.max(questions.length, 1)}
          size={96}
          strokeWidth={8}
          label={<span className={cn("text-2xl font-black", scoreTone)}>{scorePct}%</span>}
          aria-label={`Score : ${score} sur ${questions.length}`}
        />
        <div>
          <p className="flex items-center justify-center gap-1.5 text-xs font-bold uppercase tracking-wide text-muted-foreground sm:justify-start">
            <Trophy className="h-3.5 w-3.5" /> {tExam("finalScore", language)}
          </p>
          <p className="mt-1 text-4xl font-black text-foreground">
            {score} / {questions.length}
          </p>
        </div>
      </div>

      <motion.div initial="hidden" animate="show" variants={RESULTS_STAGGER_VARIANTS} className="space-y-4 sm:space-y-6">
        {questions.map((q, index) => {
          const userAnswer = answers[q.id];
          const correctOption = q.options.find((o) => o.isCorrect);
          const isCorrect = !!correctOption && userAnswer === correctOption.label;
          return (
            <motion.div
              key={q.id}
              variants={RESULT_CARD_VARIANTS}
              className="rounded-2xl border border-border bg-card p-4 shadow-soft sm:p-5"
            >
              <div className="mb-3 flex items-start justify-between gap-3">
                <p className="text-sm font-medium leading-relaxed text-foreground">
                  <span className="mr-2 font-bold text-primary-600 dark:text-primary-400">Q{index + 1}.</span>
                  {q.vignette}
                </p>
                <Badge variant={isCorrect ? "success" : "danger"} className="shrink-0">
                  {isCorrect ? <CheckCircle2 className="mr-1 h-3.5 w-3.5" /> : <XCircle className="mr-1 h-3.5 w-3.5" />}
                  {isCorrect ? "Correcte" : "Incorrecte"}
                </Badge>
              </div>

              <div className="space-y-2">
                {q.options.map((opt) => {
                  const isUserChoice = userAnswer === opt.label;
                  return (
                    <div
                      key={opt.label}
                      className={cn(
                        "flex min-h-12 items-center gap-3 rounded-xl border p-3 text-sm",
                        isUserChoice && opt.isCorrect && "border-emerald-500 bg-emerald-50 dark:border-emerald-600 dark:bg-emerald-950/30",
                        isUserChoice && !opt.isCorrect && "border-rose-500 bg-rose-50 dark:border-rose-600 dark:bg-rose-950/30",
                        !isUserChoice && opt.isCorrect && "border-dashed border-emerald-400 bg-card",
                        !isUserChoice && !opt.isCorrect && "border-border"
                      )}
                    >
                      <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-current text-xs font-bold text-muted-foreground">
                        {opt.label}
                      </span>
                      <span className="flex-1 text-foreground">{opt.text}</span>
                      {isUserChoice && opt.isCorrect && <CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600" />}
                      {isUserChoice && !opt.isCorrect && <XCircle className="h-4 w-4 shrink-0 text-rose-600" />}
                      {!isUserChoice && opt.isCorrect && (
                        <Badge variant="outline" className="shrink-0 text-[10px]">
                          Bonne réponse
                        </Badge>
                      )}
                    </div>
                  );
                })}
              </div>

              <div className="mt-4 rounded-xl border border-blue-100 bg-blue-50 p-4 dark:border-blue-900/40 dark:bg-blue-950/20">
                <p className="mb-2 flex items-center gap-1.5 text-xs font-bold uppercase tracking-wide text-blue-700 dark:text-blue-400">
                  <Sparkles className="h-3.5 w-3.5" /> Explication détaillée
                </p>
                <ul className="space-y-1.5 text-sm text-foreground">
                  {q.options.map((opt) => (
                    <li key={opt.label}>
                      <span className="font-semibold">{opt.label}.</span> {opt.explanation}
                    </li>
                  ))}
                </ul>
              </div>
            </motion.div>
          );
        })}
      </motion.div>

      {weakPoints.length > 0 && (
        <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-5 dark:border-amber-900/40 dark:bg-amber-950/20">
          <p className="mb-2.5 flex items-center gap-2 text-sm font-bold text-amber-800 dark:text-amber-300">
            <AlertTriangle className="h-4 w-4" /> Points Faibles Identifiés
          </p>
          <div className="flex flex-wrap gap-1.5">
            {weakPoints.map((point) => (
              <Badge key={point} variant="warning">
                {point}
              </Badge>
            ))}
          </div>
        </div>
      )}

      <div className="mt-6 flex flex-col gap-2.5">
        <Button variant="secondary" className="min-h-12 w-full whitespace-normal text-center leading-snug" onClick={handleStartOver}>
          <FilePlus2 className="h-4 w-4 shrink-0" />
          {tExam("generateNewExam", language)}
        </Button>
        <Button
          variant="outline"
          className="min-h-12 w-full whitespace-normal border-blue-300/60 bg-blue-50 text-center leading-snug text-blue-700 hover:bg-blue-100 dark:border-blue-800/60 dark:bg-blue-950/30 dark:text-blue-300 dark:hover:bg-blue-950/50"
          onClick={handleRegenerate}
          disabled={attempts <= 0 || isGenerating}
        >
          {isGenerating ? <Loader2 className="h-4 w-4 shrink-0 animate-spin" /> : <RotateCcw className="h-4 w-4 shrink-0" />}
          {attempts > 0
            ? tExam(attempts > 1 ? "regenerateCountPlural" : "regenerateCountSingular", language).replace("{n}", String(attempts))
            : tExam("noRegenerationsLeft", language)}
        </Button>
      </div>
    </>
  );

  const resultsContent = (
    <motion.div
      key="results"
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.35, ease: [0.22, 1, 0.36, 1] }}
      className="flex h-full flex-col overflow-y-auto p-4 pb-[calc(3rem+env(safe-area-inset-bottom))] sm:p-6"
    >
      {resultsInnerContent}
    </motion.div>
  );

  // Opens the portaled FullscreenViewerModal — no longer toggles this
  // panel's own classes to `fixed inset-0` (that silently failed: this
  // panel sits inside a `.glass-card`/panelShellClasses ancestor, and
  // `backdrop-filter` makes that ancestor the CONTAINING BLOCK for any
  // `position: fixed` descendant per the CSS spec, so the old "fullscreen"
  // div only ever filled that card's own box — the mobile tab bar and "Mes
  // Examens" list stayed visible underneath it. A portal sidesteps this
  // entirely). Shared between desktop's `main` and mobile's "Résultats" tab
  // (only one of the two ever mounts at a time).
  const fullscreenToggleRow = (
    <div className="flex shrink-0 items-center justify-end px-2 pt-2">
      <FullscreenToggleButton isFullscreen={false} onToggle={() => setIsExamFullscreen(true)} />
    </div>
  );

  return (
    // Point 2 fix — explicit w-full max-w-full alongside the existing
    // overflow-hidden, matching the sibling workspace/module page's own
    // identical root treatment.
    <div className="aurora-canvas-bg relative flex h-dvh w-full max-w-full flex-col overflow-hidden">
      <div aria-hidden className="aurora-mesh-bg animate-mesh-pulse pointer-events-none fixed inset-0 -z-10" />
      <WorkspaceTopbar title="Générateur d'Examen" />

      {/* Mobile-first UX rework — below `md`, aside/main never render side
          by side any more (there was too little room for either once one
          held a real generated exam). A "Sources" / "Résultats" tab switch
          decides which single panel shows. Desktop (md:+) keeps the
          original permanent side-by-side split, both panels always
          visible, completely unchanged. */}
      {!isDesktopOrTablet && (
        <div className="px-3 pt-3 sm:px-4">
          <SourcesResultsTabs
            active={mobileTab}
            onChange={setMobileTab}
            sourcesLabel="Sources"
            resultsLabel="Résultats"
            resultsCount={savedExams.length}
          />
        </div>
      )}

      <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-hidden p-3 sm:p-4 md:flex-row">
        {isDesktopOrTablet ? (
          <>
            {/* Panneau Gauche — Sources + Historique (desktop) */}
            <aside className={cn(panelShellClasses, "max-h-[35vh] w-full shrink-0 md:h-auto md:max-h-none md:w-80")}>
              {courseHeaderBlock}
              <ReferenceExamUploader styleProfile={styleProfile} onStyleProfileChange={setStyleProfile} disabled={isGenerating} />
              {/* min-h-0 — a flex child with overflow-y-auto silently
                  refuses to actually clip/scroll without it (flex items
                  default to min-height: auto, so they grow to fit content
                  instead of shrinking to the parent's bound). */}
              <div className="min-h-0 flex-1 overflow-y-auto p-2">
                {courseListContent}
                {savedExams.length > 0 && <div className="mt-2 border-t border-border pt-2">{savedExamsContent}</div>}
              </div>
            </aside>

            {/* Panneau Droit — Exam Arena (desktop) */}
            <main className={cn(panelShellClasses, "min-h-0 w-full flex-1")}>
              {(examState === "testing" || examState === "results") && fullscreenToggleRow}
              <AnimatePresence mode="wait">
                {examState === "idle" && idleContent}
                {examState === "generating" && generatingContent}
                {examState === "testing" && testingContent}
                {examState === "results" && resultsContent}
              </AnimatePresence>
            </main>
          </>
        ) : mobileTab === "sources" ? (
          <div className={cn(panelShellClasses, "min-h-0 w-full flex-1")}>
            {examState === "generating" ? (
              <AnimatePresence mode="wait">{generatingContent}</AnimatePresence>
            ) : (
              <>
                {courseHeaderBlock}
                <ReferenceExamUploader styleProfile={styleProfile} onStyleProfileChange={setStyleProfile} disabled={isGenerating} />
                <div className="min-h-0 flex-1 overflow-y-auto p-2">{courseListContent}</div>
                {generateButtonBlock}
              </>
            )}
          </div>
        ) : (
          <div className={cn(panelShellClasses, "min-h-0 w-full flex-1")}>
            {savedExams.length > 0 && (
              <div className="max-h-40 shrink-0 overflow-y-auto border-b border-border p-2">{savedExamsContent}</div>
            )}
            {examState === "testing" || examState === "results" ? (
              <>
                {fullscreenToggleRow}
                <AnimatePresence mode="wait">
                  {examState === "testing" && testingContent}
                  {examState === "results" && resultsContent}
                </AnimatePresence>
              </>
            ) : (
              <p className="flex-1 px-4 py-10 text-center text-xs text-muted-foreground">
                Aucun examen généré pour l&apos;instant — choisis tes cours dans l&apos;onglet « Sources », puis lance une génération.
              </p>
            )}
          </div>
        )}
      </div>

      {/* Shown whenever the "testing" state is actually the visible panel:
          always on desktop (both panels visible), only in the mobile
          "Résultats" tab (the "Sources" tab shows the source-selection
          panel instead, where this progress bar would be meaningless).
          z-[110] — ABOVE FullscreenViewerModal's own z-[100]: without that,
          taking the exam in fullscreen would visually bury this progress
          bar (and the only way to submit the exam) behind the modal it's
          meant to float on top of. This bar is its own independent `fixed`
          element directly under the page root (no `.glass-card` ancestor
          in between), so unlike the old per-panel fullscreen div it never
          had the backdrop-filter containing-block problem — only its
          z-index needed to move. */}
      {examState === "testing" && (isDesktopOrTablet || mobileTab === "results") && (
        <div className="glass-panel fixed inset-x-0 bottom-0 z-[110] flex items-center justify-between gap-3 p-4 pb-[calc(1rem+env(safe-area-inset-bottom))] shadow-glass dark:shadow-glass-dark">
          <div className="hidden items-center gap-3 sm:flex">
            <Button
              variant="outline"
              size="sm"
              className="min-h-12 w-12 p-0"
              aria-label="Question précédente"
              disabled={currentQuestionIndex === 0}
              onClick={() => goToQuestion(currentQuestionIndex - 1)}
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <p className="text-sm text-muted-foreground">
              <ListChecks className="mr-1.5 inline h-4 w-4" />
              {answeredCount} / {questions.length} questions répondues
            </p>
            <Button
              variant="outline"
              size="sm"
              className="min-h-12 w-12 p-0"
              aria-label="Question suivante"
              disabled={currentQuestionIndex >= questions.length - 1}
              onClick={() => goToQuestion(currentQuestionIndex + 1)}
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
          <Button className="min-h-12 w-full shadow-glow sm:w-auto" onClick={handleFinishExam} disabled={isSavingAttempt} isLoading={isSavingAttempt}>
            Afficher la correction
          </Button>
        </div>
      )}

      <FullscreenViewerModal
        open={isExamFullscreen}
        onClose={() => setIsExamFullscreen(false)}
        title={examState === "results" ? "Résultats de l'examen" : "Épreuve Clinique"}
      >
        <div className="p-4 sm:p-6">{examState === "testing" ? testingInnerContent : examState === "results" ? resultsInnerContent : null}</div>
      </FullscreenViewerModal>
    </div>
  );
}
