"use client";

import { useEffect, useRef, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { AlertTriangle, ArrowLeft, Loader2 } from "lucide-react";
import { SourcesSidebar } from "@/components/course/workspace/SourcesSidebar";
import { CenterReader } from "@/components/course/workspace/CenterReader";
import { StudioSidebar } from "@/components/course/workspace/StudioSidebar";
import { ChatPanel } from "@/components/course/workspace/ChatPanel";
import type { ChatMessage, ContentType, Course } from "@/lib/types";

function buildAskPrompt(selectedText: string): string {
  return `L'étudiant demande une explication détaillée sur ce passage précis de son cours de médecine : "${selectedText}". Explique-le comme un professeur de manière simple et précise.`;
}

function buildTranslatePrompt(selectedText: string): string {
  return `Traduis ce terme ou passage médical en arabe et en français courant : "${selectedText}".`;
}

export default function CoursePage() {
  const params = useParams<{ id: string }>();
  const id = params.id;

  const [course, setCourse] = useState<Course | null | undefined>(undefined);
  const [cachedContent, setCachedContent] = useState<Partial<Record<ContentType, string>>>({});
  const [activeContentType, setActiveContentType] = useState<ContentType>("cours_oral");
  const [loadingContentType, setLoadingContentType] = useState<ContentType | null>(null);
  const [contentError, setContentError] = useState<{ type: ContentType; message: string } | null>(
    null
  );

  const [chatOpen, setChatOpen] = useState(false);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [chatInput, setChatInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);

  const autoGeneratedOral = useRef(false);

  useEffect(() => {
    let cancelled = false;
    setCourse(undefined);

    fetch(`/api/courses/${id}`)
      .then((res) => (res.ok ? res.json() : Promise.reject()))
      .then((data) => {
        if (cancelled) return;
        setCourse(data.course);
        setCachedContent(data.cachedContent ?? {});
      })
      .catch(() => {
        if (!cancelled) setCourse(null);
      });

    return () => {
      cancelled = true;
    };
  }, [id]);

  useEffect(() => {
    if (!course || course.status !== "ready") return;
    if (cachedContent.cours_oral || autoGeneratedOral.current) return;
    autoGeneratedOral.current = true;
    void loadContent("cours_oral");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [course, cachedContent.cours_oral]);

  async function loadContent(contentType: ContentType) {
    setActiveContentType(contentType);
    setContentError(null);

    if (cachedContent[contentType]) return;

    setLoadingContentType(contentType);

    try {
      const res = await fetch(`/api/courses/${id}/generate`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ contentType }),
      });
      const data = await res.json();

      if (!res.ok) {
        setContentError({ type: contentType, message: data.error ?? "La génération a échoué." });
        return;
      }

      setCachedContent((prev) => ({ ...prev, [contentType]: data.content }));
    } catch {
      setContentError({ type: contentType, message: "Impossible de contacter le serveur." });
    } finally {
      setLoadingContentType(null);
    }
  }

  async function sendChatMessage(content: string) {
    const userMessage: ChatMessage = { id: crypto.randomUUID(), role: "user", content };
    const history = [...chatMessages, userMessage];
    setChatMessages(history);
    setChatOpen(true);
    setIsTyping(true);

    try {
      const res = await fetch("/api/chat", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          courseId: id,
          messages: history.map((m) => ({ role: m.role, content: m.content })),
        }),
      });
      const data = await res.json();

      const reply: ChatMessage = {
        id: crypto.randomUUID(),
        role: "assistant",
        content: res.ok ? data.reply : data.error ?? "Une erreur est survenue.",
      };
      setChatMessages((prev) => [...prev, reply]);
    } catch {
      setChatMessages((prev) => [
        ...prev,
        { id: crypto.randomUUID(), role: "assistant", content: "Impossible de contacter le serveur." },
      ]);
    } finally {
      setIsTyping(false);
    }
  }

  function handleAsk(selectedText: string) {
    void sendChatMessage(buildAskPrompt(selectedText));
  }

  function handleTranslate(selectedText: string) {
    void sendChatMessage(buildTranslatePrompt(selectedText));
  }

  function handleChatSubmit() {
    const text = chatInput.trim();
    if (!text) return;
    setChatInput("");
    void sendChatMessage(text);
  }

  if (course === undefined) {
    return (
      <div className="flex h-screen w-full items-center justify-center bg-[#F9FAFB]">
        <Loader2 className="h-6 w-6 animate-spin text-primary-600" />
      </div>
    );
  }

  if (course === null) {
    return (
      <div className="flex h-screen w-full flex-col items-center justify-center gap-4 bg-[#F9FAFB] text-center">
        <h1 className="text-xl font-bold text-foreground">Cours introuvable</h1>
        <p className="text-sm text-muted-foreground">Ce cours n'existe pas, ou ne t'appartient pas.</p>
        <Link
          href="/dashboard"
          className="inline-flex items-center gap-1.5 text-sm font-medium text-primary hover:underline"
        >
          <ArrowLeft className="h-4 w-4" />
          Retour au tableau de bord
        </Link>
      </div>
    );
  }

  if (course.status !== "ready") {
    return (
      <div className="flex h-screen w-full flex-col items-center justify-center gap-4 bg-[#F9FAFB] px-6 text-center">
        {course.status === "processing" ? (
          <>
            <Loader2 className="h-6 w-6 animate-spin text-amber-600" />
            <p className="text-sm text-amber-800">L'IA analyse encore ce cours — reviens dans un instant.</p>
          </>
        ) : (
          <>
            <AlertTriangle className="h-6 w-6 text-red-600" />
            <p className="text-sm text-red-800">{course.errorMessage ?? "La génération a échoué."}</p>
          </>
        )}
        <Link
          href="/dashboard"
          className="inline-flex items-center gap-1.5 text-sm font-medium text-primary hover:underline"
        >
          <ArrowLeft className="h-4 w-4" />
          Retour au tableau de bord
        </Link>
      </div>
    );
  }

  return (
    <div className="flex h-screen w-full overflow-hidden bg-[#F9FAFB]">
      <SourcesSidebar course={course} />

      <CenterReader
        content={cachedContent[activeContentType] ?? null}
        isLoading={loadingContentType === activeContentType}
        error={contentError?.type === activeContentType ? contentError.message : null}
        onAsk={handleAsk}
        onTranslate={handleTranslate}
      />

      <StudioSidebar
        activeContentType={activeContentType}
        loadingContentType={loadingContentType}
        onSelect={loadContent}
        onOpenChat={() => setChatOpen(true)}
      />

      <ChatPanel
        open={chatOpen}
        onClose={() => setChatOpen(false)}
        messages={chatMessages}
        isTyping={isTyping}
        input={chatInput}
        onInputChange={setChatInput}
        onSend={handleChatSubmit}
      />
    </div>
  );
}
